### ISSUE TITLE
Feat: Add Cylance software

### ISSUE THREAD

**Issue by agt24** [tr3kl0v/stop-sauron#18]
First, thank you! I love this script.

but my Mac has one more little Orc...

```
(base) ➜/tmp # ps aux | grep Cylance
root               161   3.1  0.4  6807900 276252   ??  Ss   Mon01PM  15:16.18 /Library/Application Support/Cylance/Desktop/CylanceSvc.app/Contents/MacOS/CylanceSvc
```

**Comment by tr3kl0v** [comment]
I'm working on this, but I lack the daemon processes of Cylance? Can you run:

1. $ launchctl list | grep -E 'cyclane|cy'
2. $ sudo launchctl list | grep -E 'cyclane|cy'

And share both lists with me?

I expect some like "CylanceSv"c and "CyUpdate" --> https://docs.blackberry.com/en/unified-endpoint-security/blackberry-ues/release-notes/Protect-desktop-release-notes/Whats-new-in-the-Protect-Desktop-agent-for-macOS/Fixed-issues-in-the-macOS-agent

**Comment by agt24** [comment]
Sorry for the delay. First list:

```
-	0	com.cylancePROTECT
1995	0	com.apple.ap.adprivacyd
6206	0	com.apple.transparencyd
-	0	com.apple.storelegacy
```


Second list:

```
-	0	com.cylance.cylancees
201	0	com.apple.displaypolicyd
803	0	com.apple.AccountPolicyHelper
161	0	com.cylance.agent_service
222	0	com.apple.security.syspolicy
3073	0	com.apple.dprivacyd
```

**Comment by tr3kl0v** [comment]
👋  agt24. The configuration has been added. Can you test out this branch: https://github.com/tr3kl0v/stop-sauron/tree/18-feat-add-cylance-software and let me know if it works? Please use the -x option for eventual debugging (./stop-sauron.sh -x)

The worst that can happen is that you need to launch the daemons/agents manual. (e.g. sudo launchctl load /Library/launchdaemons/com.cylance.agent_service.plist)
